SportoStoroTorro/Controllers/NavController.cs
using DataLogic.Repositories.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportoStoroTorro.Controllers
{
    public class NavController : Controller
    {
        private IProductRepository repository;
        // GET: Nav

        public NavController(IProductRepository repo)
        {
            this.repository = repo;
        }
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products.Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

SportoStoroTorro/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="message">@TempData["message"] </div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportoStoroTorro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")*@
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
  <div id="header">
      @{Html.RenderAction("Summary", "Cart");}
      <div class="title">
          Sklep sportowy
      </div>
  </div>
    <div id="categories">
        @{Html.RenderAction("Menu", "Nav");}
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>