SportoStoroTorro/Controllers/AdminController.cs
using DataLogic.BusinessObjects.Contract;
using DataLogic.BusinessObjects.Implementation;
using DataLogic.Repositories.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportoStoroTorro.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IProductRepository repository;

        public AdminController(IProductRepository repo)
        {
            repository = repo;
        }


        // GET: Admin
        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int ProductID)
        {
            IProduct product = repository.Products.FirstOrDefault(p => p.ProductID == ProductID);
            return View(product);
        }

        public ActionResult Edit(IProduct product, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = string.Format("Zapisano {0} ", product.Name);
                return RedirectToAction("Index");

            }
            else
            {
                return View(product as Product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            IProduct deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("Usunieto {0}", deletedProduct.Name);
            }
            return RedirectToAction("Index");

        }
    }
}

SportoStoroTorro/Controllers/ProductController.cs
using DataLogic.BusinessObjects.Contract;
using DataLogic.BusinessObjects.Implementation;
using DataLogic.Repositories.Contract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportoStoroTorro.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository prodRep)
        {
            this.repository = prodRep;
        }
        //
        // GET: /Product/
        public ActionResult Index()
        {
            return View();
        }

        public FileContentResult GetImage(int productId)
        {
            IProduct prod = repository.Products.FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }

        public ViewResult List(string category,int page = 1)
        {
            ProductListViewModel viewModel = new ProductListViewModel()
            {
                Products = repository.Products.OrderBy(p=> p.ProductID)
                .Where(p => category == null || p.Category == category)
                .Skip((page-1)*PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? repository.Products.Count() : repository.Products.Where(e=> e.Category == category).Count()
                },
                CurrentCategory = category
            };

            return View(viewModel);
          
        }
    }
}

SportoStoroTorro/Views/Admin/Edit.cshtml
@model DataLogic.BusinessObjects.Implementation.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit @Model.Name</h2>

@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.EditorForModel()
    <div class="editor-label">Zdjecie</div>
    <div class="editor-field">
        @if (Model.ImageData == null)
        {
            @:Brak
	}
        else
        {
            <img width="150" height="150" src="@Url.Action("GetImage", "Product", new {Model.ProductID})" />
        }
        <div>Przeslij nowe zdjecie: <input type="file" name="Image" /></div>

    </div>

    <input type="submit" value="Zapisz" />
    @Html.ActionLink("Anuluj i wroc do listy", "Index");
}

SportoStoroTorro/Views/Admin/Index.cshtml
@model IEnumerable<DataLogic.BusinessObjects.Implementation.Product>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>nazwa</th>
        <th class="numericCol">cena </th>
        <th>Akcje</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ProductID</td>
       <td>
           @Html.ActionLink(item.Name, "Edit", new { item.ProductID})
       </td>
            <td>
                @using (Html.BeginForm("Delete", "Admin"))
                {
                    @Html.Hidden("ProductID", item.ProductID)
                    <input type="submit" value="Usun" />
                }
            </td>
    </tr>
    }

</table>